language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
    - sudo apt-get -y update
    - sudo apt-get -y update
    - sudo apt-get -y install r-base
    - sudo apt-get -y install python-matplotlib
    - pip install codecov
    - pip install -r requirements.txt
    - cd wext
    - python setup.py install
    - cd ../
    ##- f2py -c wext/src/fortran/bipartite_edge_swap_module.f95 -m bipartite_edge_swap_module
    - pwd
    - ls
script:
    - nosetests
after_success:
    - codecov
